version: "3.8"

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - mysqldb:/var/lib/mysql

  web:
    build:
      context: ./docker
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysqldb:
